server:
  port: 8001

storage-dir: dataStore

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graph?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: aptx4869
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml