server:
  port: 8001

storage-dir: dataStore

spring:
  datasource:
    url: jdbc:mysql://118.182.96.49:3307/graph?characterEncoding=utf-8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/graph?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    #password: aptx4869
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://admin:xixi12345678@121.36.13.224:27017/coin?authSource=admin

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml

token:
  tokenExpireTime: 30